"""
TEST CNR_PARAM LIBRARY
"""
import os
from launch import LaunchDescription
from launch_ros.actions import Node

from ament_index_python.packages import get_package_share_directory


def generate_launch_description():
    """
    Generates the launch description for the test.

    Returns:
        LaunchDescription: The launch description object.
        dict: The locals dictionary.
    """
    ld = LaunchDescription()

    config = os.path.join(
        get_package_share_directory('cnr_param_tests'),
        'config',
        'ros2parameters.yaml'
    )
    config2 = os.path.join(
        get_package_share_directory('cnr_param_tests'),
        'config',
        'par_autogenerated.yaml'
    )
    generic_node_with_parameters = Node(
        package='cnr_param_tests',
        name='ros2_parameters_server_node',
        executable='ros2_parameters_server_node',
        parameters=[config, config2],
        output='screen',
        emulate_tty=True
    )

    cnr_param_getter_node = Node(
        package='cnr_param_tests',
        name='ros2_parameters_client_node',
        executable='ros2_parameters_client_node',
        output='screen',
        emulate_tty=True
    )

    ld.add_action(generic_node_with_parameters)
    ld.add_action(cnr_param_getter_node)

    return ld
