set(cnr_param_BUILD_AS_A_CATKIN_PACKAGE  ON )
set(cnr_param_BUILD_AS_AN_AMENT_PACKAGE  OFF )
set(cnr_param_COMPILE_ROS1_MODULE        OFF )
set(cnr_param_COMPILE_ROS2_MODULE        OFF )
set(cnr_param_COMPILE_MAPPED_FILE_MODULE ON )
