# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget cnr_param_utilities cnr_param_server cnr_param_server_utilities)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target cnr_param_utilities
add_library(cnr_param_utilities SHARED IMPORTED)

set_target_properties(cnr_param_utilities PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include;/usr/include/eigen3;/home/jacobi/projects/cari_motion_planning/cnr_param/include"
  INTERFACE_LINK_LIBRARIES "yaml-cpp;Boost::system;Boost::filesystem;Eigen3::Eigen"
)

# Create imported target cnr_param_server
add_executable(cnr_param_server IMPORTED)

set_target_properties(cnr_param_server PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/jacobi/projects/cari_motion_planning/cnr_param/include"
)

# Create imported target cnr_param_server_utilities
add_library(cnr_param_server_utilities SHARED IMPORTED)

set_target_properties(cnr_param_server_utilities PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include;/usr/include/eigen3;/home/jacobi/projects/cari_motion_planning/cnr_param/include"
  INTERFACE_LINK_LIBRARIES "cnr_param_utilities;Boost::program_options;Boost::iostreams;Boost::regex"
)

# Import target "cnr_param_utilities" for configuration "Release"
set_property(TARGET cnr_param_utilities APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(cnr_param_utilities PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/jacobi/projects/cari_motion_planning/cnr_param/cmake/libcnr_param_utilities.so"
  IMPORTED_SONAME_RELEASE "libcnr_param_utilities.so"
  )

# Import target "cnr_param_server" for configuration "Release"
set_property(TARGET cnr_param_server APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(cnr_param_server PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/jacobi/projects/cari_motion_planning/cnr_param/cmake/cnr_param_server"
  )

# Import target "cnr_param_server_utilities" for configuration "Release"
set_property(TARGET cnr_param_server_utilities APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(cnr_param_server_utilities PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/jacobi/projects/cari_motion_planning/cnr_param/cmake/libcnr_param_server_utilities.so"
  IMPORTED_SONAME_RELEASE "libcnr_param_server_utilities.so"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
