name: 'Build using plain cmake'

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'docs/**'
    - 'README.md'
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu 22.04", 
            artifact: "Linux.tar.xz",
            os: ubuntu-22.04,
            build_type: "Debug", cc: "gcc", cxx: "g++", cmake_version_used: "3.16.2"
          }
        - {
            name: "Ubuntu 24.04", 
            artifact: "Linux.tar.xz",
            os: ubuntu-24.04,
            build_type: "Debug", cc: "gcc", cxx: "g++", cmake_version_used: "3.16.2"
          }
        - {
            name: "Ubuntu 20.04", 
            artifact: "Linux.tar.xz",
            os: ubuntu-24.04,
            build_type: "Debug", cc: "gcc", cxx: "g++", cmake_version_used: "3.16.2"
          }
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      if: ${{ runner.os == 'Linux' }}
      run: sudo apt-get update && 
            sudo apt-get install -y --fix-missing git python3-pip sudo &&
              python -m pip install -U colcon-common-extensions &&
                python -m pip install -U vcstool &&  
                  python -m pip install -U rosdep &&
                    sudo rosdep init && 
                      rosdep update
    - name: Install Windows dependencies
      if: ${{ runner.os == 'Windows' }}
      run: winget install Git.Git Kitware.CMake Python.Python.3.13 cURL.cURL Ninja-build.Ninja
    - name: Install Python PIP for windows
      if: ${{ runner.os == 'Windows' }}
      run: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python get-pip.py
    - name: Install Python modules via PIP
      if: ${{ runner.os == 'Windows' }}
      run: python -m pip install colcon vcstool rosdep
    - name: Configure
      run: cmake
            -S .
            -B build
            -D CMAKE_BUILD_TYPE=${{ matrix.config.build_type }}
            -D RETRIVE_DEPENDENCIES=ON
            -D BUILD_AS_A_CATIKIN_PACKAGE=OFF
            -D COMPILE_ROS1_MODULE=OFF
            -D COMPILE_ROS2_MODULE=OFF
            -D COMPILE_MAPPED_FILE_MODULE=ON
            -D BUILD_UNIT_TESTS=OFF
            -D BUILD_INTEGRATION_TESTS=OFF
    - name: Build
      run: cmake --build build
